background            #0A0F1F
foreground            #FFFFFF

# black
color0  #0A0F1F
color8  #FF4F00

# red
color1  #647cb4
color9  #FF7A3F

# green
color2  #87a1c4
color10 #E8B050

# yellow
color3  #5A6A8A
color11 #A0D070

# blue
color4  #B0B8D0
color12 #60B0FF

# magenta
color5  #F0F0F5
color13 #FF4F00

#cyan
color6  #F8F8FA
color14 #50E0E0

#white
color7  #FFFFFF
color15 #FF9A70


